# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
np.version.version

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [20]:
# Method 1
a=np.random.random((2,3,5))

In [12]:
# Method 2
a=np.random.rand(2,3,5)

In [43]:
# Method 3


#### 4. Print *a*.


In [14]:
a

array([[[0.15832418, 0.41704024, 0.80223012, 0.09575815, 0.43431033],
        [0.90935806, 0.97093351, 0.57115748, 0.03058772, 0.92488162],
        [0.79235871, 0.80875024, 0.29840891, 0.55904222, 0.39506825]],

       [[0.02037688, 0.15007628, 0.5398516 , 0.07787497, 0.7472635 ],
        [0.51763161, 0.94901385, 0.03705768, 0.40290344, 0.31469251],
        [0.32029129, 0.04087139, 0.70734768, 0.01086463, 0.16899251]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [30]:
# your code here
b=np.full((5,2,3),1,dtype=float)


In [45]:
c.shape

(3, 2, 5)

#### 6. Print *b*.


In [31]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [32]:
# your code here
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [33]:
# your answer here
#It is impossible because although sizes are the same, the dimensions are different (number of matrices, rows, and columns don't match)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [57]:
# your code here
c=b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [51]:
# your code/answer here
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [52]:
# your code/answer here
a

array([[[0.10786921, 0.21501753, 0.27012551, 0.11762769, 0.08387031],
        [0.70231333, 0.99306893, 0.81708613, 0.02897592, 0.65605751],
        [0.82660247, 0.92488758, 0.91716297, 0.65069761, 0.01736086]],

       [[0.08342815, 0.86327547, 0.79268952, 0.91637133, 0.02896291],
        [0.48450362, 0.20826087, 0.36082381, 0.0776481 , 0.99844238],
        [0.18987571, 0.77616665, 0.30596768, 0.7178042 , 0.76949504]]])

In [53]:
d

array([[[1.10786921, 1.21501753, 1.27012551, 1.11762769, 1.08387031],
        [1.70231333, 1.99306893, 1.81708613, 1.02897592, 1.65605751],
        [1.82660247, 1.92488758, 1.91716297, 1.65069761, 1.01736086]],

       [[1.08342815, 1.86327547, 1.79268952, 1.91637133, 1.02896291],
        [1.48450362, 1.20826087, 1.36082381, 1.0776481 , 1.99844238],
        [1.18987571, 1.77616665, 1.30596768, 1.7178042 , 1.76949504]]])

In [ ]:
#d= 1 + a
#because c array values are all equal to 1

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [56]:
e=a*c
e

array([[[0.10786921, 0.21501753, 0.27012551, 0.11762769, 0.08387031],
        [0.70231333, 0.99306893, 0.81708613, 0.02897592, 0.65605751],
        [0.82660247, 0.92488758, 0.91716297, 0.65069761, 0.01736086]],

       [[0.08342815, 0.86327547, 0.79268952, 0.91637133, 0.02896291],
        [0.48450362, 0.20826087, 0.36082381, 0.0776481 , 0.99844238],
        [0.18987571, 0.77616665, 0.30596768, 0.7178042 , 0.76949504]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [55]:
# your code/answer here
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [ ]:
#e==a because both have e values are basically a values multiplied by 1.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [60]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [63]:
# your code here
f=np.empty((2,3,5))
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [76]:
# your code here
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k]<d_mean and d[i,j,k]>d_min:
                f[i,j,k]=25
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_max:
                f[i,j,k]=100
            

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [74]:
# your code here
d

array([[[1.10786921, 1.21501753, 1.27012551, 1.11762769, 1.08387031],
        [1.70231333, 1.99306893, 1.81708613, 1.02897592, 1.65605751],
        [1.82660247, 1.92488758, 1.91716297, 1.65069761, 1.01736086]],

       [[1.08342815, 1.86327547, 1.79268952, 1.91637133, 1.02896291],
        [1.48450362, 1.20826087, 1.36082381, 1.0776481 , 1.99844238],
        [1.18987571, 1.77616665, 1.30596768, 1.7178042 , 1.76949504]]])

In [75]:
f

array([[[ 25.,  25.,  25.,  25.,  25.],
        [ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,   0.]],

       [[ 25.,  75.,  75.,  75.,  25.],
        [ 25.,  25.,  25.,  25., 100.],
        [ 25.,  75.,  25.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [86]:
f=f.astype(np.str_)

In [87]:
# your code here

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k]<d_mean and d[i,j,k]>d_min:
                f[i,j,k]='B'
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]='D'
            elif d[i,j,k]==d_mean:
                f[i,j,k]='C'
            elif d[i,j,k]==d_min:
                f[i,j,k]='A'
            elif d[i,j,k]==d_max:
                f[i,j,k]='E'

In [88]:
f

array([[['B', 'B', 'B', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'D', 'D', 'A']],

       [['B', 'D', 'D', 'D', 'B'],
        ['B', 'B', 'B', 'B', 'E'],
        ['B', 'D', 'B', 'D', 'D']]], dtype='<U32')